/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "my.h"


void
my_rpc_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	my_io_data_t  my_rpcc_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MY_RPC_PROG, MY_RPC_VERS1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = my_rpcc_1(&my_rpcc_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
my_rpc_prog_2(char *host)
{
	CLIENT *clnt;
	my_io_data_t  *result_1;
	my_io_data_t  my_rpcc_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MY_RPC_PROG, MY_RPC_VERS2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
        my_rpcc_2_arg.mtype = 3;
        my_rpcc_2_arg.len = 18;
	result_1 = my_rpcc_2(&my_rpcc_2_arg, clnt);
	if (result_1 == (my_io_data_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
        fprintf(stderr, "recv msg from server! mtype:%d len:%d \n",result_1->mtype,result_1->len);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	//my_rpc_prog_1 (host);
	my_rpc_prog_2 (host);
exit (0);
}
