/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "my.h"

int *
my_rpcc_1_svc(my_io_data_t *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

my_io_data_t *
my_rpcc_2_svc(my_io_data_t *argp, struct svc_req *rqstp)
{
	static my_io_data_t  result;

	/*
	 * insert server code here
	 */
        printf("recv msg from client! len:%d, mtype:%d \n",argp->len,argp->mtype);
        result.mtype = 33;
        result.len = 12;
	return &result;
}
